authentik:
    error_reporting:
        enabled: true
    log_level: info
server:
    ingress:
        enabled: true
    livenessProbe:
        initialDelaySeconds: 120
        periodSeconds: 60
    resources:
        limits:
            cpu: 1000m
            memory: 768Mi
    metrics:
        serviceMonitor:
            create: true
        rules:
            create: true
postgresql:
    enabled: true
    resources:
        limits:
            cpu: 1000m
            memory: 256Mi
    primary:
        persistence:
            annotations:
                helm.sh/resource-policy: keep
redis:
    enabled: true
    resources:
        limits:
            cpu: 1000m
            memory: 256Mi
    master:
        persistence:
            annotations:
                helm.sh/resource-policy: keep
worker:
    resources:
        limits:
            cpu: 1000m
            memory: 768Mi
    