authentik:
    error_reporting:
        enabled: true
    log_level: info
ingress:
    enabled: true
    hosts:
        - host: COMPLETED_BY_TERRAFORM
          paths:
              - path: "/"
                pathType: Prefix
postgresql:
    enabled: true
    resources:
        limits:
            cpu: 1000m
            memory: 256Mi
redis:
    enabled: true
    resources:
        limits:
            cpu: 1000m
            memory: 256Mi
livenessProbe:
    initialDelaySeconds: 120
    periodSeconds: 60
prometheus:
    serviceMonitor:
        create: true
    rules:
        create: true
resources:
    server:
        limits:
            cpu: 1000m
            memory: 768Mi
    worker:
        limits:
            cpu: 1000m
            memory: 512Mi
    