apiVersion: apiserver.config.k8s.io/v1beta1
kind: AuthenticationConfiguration
jwt:
- issuer:
    url: https://authentik.dev.gwen.org.uk
    discoveryURL: https://authentik.dev.gwen.org.uk/application/o/kubernetes-api/.well-known/openid-configuration
    audiences:
    - kubernetes-api
    audienceMatchPolicy: MatchAny
  claimValidationRules:
  claimMappings:
  userValidationRules:
  - expression: "!user.username.startsWith('system:')"
    message: 'username cannot used reserved system: prefix'
  - expression: "user.groups.all(group, !group.startsWith('system:'))"
    message: 'groups cannot used reserved system: prefix'

