apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: palworld-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 16Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: palworld-deployment
  labels:
    app: palworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: palworld
  template:
    metadata:
      labels:
        app: palworld
    spec:
      volumes:
      - name: palworld-pv-storage
        persistentVolumeClaim:
          claimName: palworld-pv-claim
      containers:
      - name: palworld
        image: ghcr.io/thijsvanloef/palworld-server-docker:v0.35.1
        ports:
        - containerPort: 8211
          protocol: UDP
        - containerPort: 27015
          protocol: UDP
        volumeMounts:
        - mountPath: "/palworld/"
          name: palworld-pv-storage
        env:
        - name: PUID
          value: "1000"
        - name: PGUID
          value: "1000"
        - name: PORT
          value: "8211"
        - name: SERVER_PASSWORD
          value: "PASSWORD"
        - name: COMMUNITY
          value: "false"
        resources:
          limits:
            memory: 20
            cpu: 4
---
# Something is wrong here
apiVersion: v1
kind: Service
metadata:
  name: palworld
spec:
  type: NodePort
  selector:
    app: palworld
  ports:
    - name: palworld1
      protocol: UDP
      port: 8211
      targetPort: 30211
    - name: palworld2
      protocol: UDP
      port: 27015
      targetPort: 30215